### ISSUE TITLE
"obsolete" function

### ISSUE THREAD

**Issue by alphapapa** [debugfan/popup-edit-menu#2]
Hi, I noticed the help for `popup-edit-menu` says the function is obsolete.  I think you need to remove https://github.com/debugfan/popup-edit-menu/blob/master/popup-edit-menu.el#L148

**Comment by debugfan** [comment]
@alphapapa Yeah, I agreed too. But this function is originally based on function "mouse-popup-menubar-stuff" in mouse.el, which is also tagged obsolete by Emacs developers. I don't know why they obsolete it, maybe a new feature will instead of it or have, or just feel no use, or just handled by automatically tools. I don't know, so I just keep it to wait on watch.

**Comment by alphapapa** [comment]
That's very interesting!  I tracked the original `make-obsolete` down to this commit from 2008 https://github.com/emacs-mirror/emacs/commit/0b2b62ff6dcaf77d2897a284013af3ff4b8ae268#diff-415005579e48588996d662bdba3ef8c0R290 and I can't figure out why it would be marked as obsolete.  You can see there that it has no `CURRENT-NAME` argument, just `nil`, indicating that there is not a newer name that replaces the existing name.  Then 10 days later someone added version numbers: https://github.com/emacs-mirror/emacs/commit/5e38cdab4557f98e14f0cfcb82d7011ded032c29, and then 4 years later someone else changed them to the `declare` forms: https://github.com/emacs-mirror/emacs/commit/59f7af816e98a74abf42d724bcfdfa9bfe9964ce

Looking at the first commit, you can see that some of the `make-obsolete`s did have `CURRENT-NAME` specified, so I think that marking this function as obsolete may have been a mistake.  9 years later and it still doesn't have a `CURRENT-NAME`, so it's still not obsolete.

Anyway, since your function copies the code in `mouse-popup-menubar-stuff`, your function is not obsolete.  The concern would be if any of the functions it calls are obsolete, in which case it should call the newer names instead.

So I think you're clear to remove the obsolete.  :)

**Comment by debugfan** [comment]
Very useful information you provided! I thought they're new changes, then I follow the histories you provided, and found that actually they are not. You are so meticulous, and thank you for giving improvement!
